# Generated by Django 4.2.5 on 2023-09-13 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='글 제목')),
                ('content', models.TextField(verbose_name='글 내용')),
                ('published_date', models.DateTimeField(verbose_name='업로드 날짜')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='유저 아이디')),
                ('user_pw', models.CharField(max_length=300, verbose_name='유저 비밀번호')),
                ('user_name', models.CharField(max_length=20, verbose_name='유저 이름')),
                ('user_email', models.EmailField(max_length=100, verbose_name='유저 이메일')),
            ],
        ),
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='post/%Y/%m/%d')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.post')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.user', verbose_name='작성자'),
        ),
    ]
