# Generated by Django 4.2.5 on 2023-09-11 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Post2',
        ),
    ]
