# Generated by Django 4.2.5 on 2023-09-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_rename_post_post2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title2', models.CharField(max_length=200)),
                ('content2', models.TextField()),
                ('published_date2', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post2',
        ),
    ]
