# Generated by Django 4.2.5 on 2023-09-11 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogapp", "0003_post5_delete_post2"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", models.TextField()),
                ("published_date", models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name="Post5",
        ),
    ]
